name: 'Libre DevOps – Terraform Free Form for Azure'
description: 'Run terraform comands freely - You should not use this unless you must ⚠️'
author: 'Craig Thacker (craig@craigthacker.dev)'
branding:
  icon: terminal
  color: green

permissions:
  id-token: write
  contents: read

inputs:
  terraform-code-location:
    description: 'Path to Terraform code'
    required: false
    default: 'examples'
    
  terraform-arguements:
    description: 'Terraform command line arguments to pass to terraform apply'
    required: true
    default: ''

  use-azure-client-secret-login:
    description: 'Authenticate via client secret'
    required: false
    default: 'false'

  use-azure-oidc-login:
    description: 'Authenticate via OIDC'
    required: false
    default: 'true'

  use-azure-user-login:
    description: 'Authenticate via device-code (user)'
    required: false
    default: 'false'

  use-azure-managed-identity-login:
    description: 'Authenticate via managed identity'
    required: false
    default: 'false'

  backend-use-azure-ad-auth:
    description: 'Backend auth via Azure AD'
    required: false
    default: 'true'

  target-subscription-id:
    description: 'Override subscription ID'
    required: false
    default: ''

  allow-no-subscriptions:
    description: 'Use no subs'
    required: false
    default: false

  arm-tenant-id:
    description: 'Azure Tenant ID for the service connection / login'
    required: false
    default: ''

  arm-subscription-id:
    description: 'Azure Subscription ID for the service connection / login'
    required: false
    default: ''

  arm-client-id:
    description: 'Azure Client ID for the service connection / login'
    required: false
    default: ''

  arm-client-secret:
    description: 'Azure Client Secret (only needed when client-secret flow is used)'
    required: false
    default: ''

  azure-credentials:
    description: 'Full JSON credentials block for azure/login when using client-secret auth'
    required: false
    default: ''



runs:
  using: composite
  steps:
    # ---------- OIDC --------------------------------------------------------
    - name: Azure Login (OIDC)
      if: ${{ inputs.use-azure-oidc-login == 'true' }}
      uses: azure/login@v2
      with:
        tenant-id:       ${{ inputs.arm-tenant-id }}
        subscription-id: ${{ inputs.target-subscription-id != '' && inputs.target-subscription-id || inputs.arm-subscription-id }}
        client-id:       ${{ inputs.arm-client-id }}
        allow-no-subscriptions: ${{ inputs.allow-no-subscriptions }}


    # ---------- Client Secret ----------------------------------------------
    - name: Azure Login (Client Secret)
      if: ${{ inputs.use-azure-client-secret-login == 'true' }}
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure-credentials }}
        allow-no-subscriptions: ${{ inputs.allow-no-subscriptions }}

    # ---------- Managed Identity -------------------------------------------
    - name: Azure Login (Managed Identity)
      if: ${{ inputs.use-azure-managed-identity-login == 'true' }}
      uses: azure/login@v2
      with:
        auth-type: ManagedIdentity
        subscription-id:        ${{ inputs.arm-subscription-id }}
        allow-no-subscriptions: ${{ inputs.allow-no-subscriptions }}

    # ---------- Main script -------------------------------------------------
    - name: Run Terraform ${{ inputs.terraform-arguements }}
      shell: pwsh
      env:
        ARM_SUBSCRIPTION_ID:  ${{ inputs.target-subscription-id != '' && inputs.target-subscription-id || inputs.arm-subscription-id }}
        ARM_USE_AZUREAD:      ${{ inputs.backend-use-azure-ad-auth }}
        ARM_USE_OIDC:         ${{ inputs.use-azure-oidc-login }}
        ARM_USE_MSI:          ${{ inputs.use-azure-managed-identity-login }}
        ARM_CLIENT_SECRET:    ${{ inputs.arm-client-secret }}
      run: |
        terraform ${{ inputs.terraform-arguments }}
